name: protein-tools
services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    environment:
      - PYTHONPATH=/app
      - AF_DB_DIR=/data/datasets/alphafold
      - MPNN_PYTHON=python3
      - MPNN_SCRIPT=/data/tools/proteinmpnn_official/protein_mpnn_run.py
      - MPNN_WEIGHTS_DIR=/data/tools/proteinmpnn_official/vanilla_model_weights
      - JOBS_DIR=/data/appjobs
    ports:
      - "8000:8000"
    volumes:
      # Tools (read-only)
      - /data/tools:/data/tools:ro
      # AlphaFold databases (read-only)
      - /data/datasets/alphafold:/data/datasets/alphafold:ro
      # Persist job outputs
      - /data/appjobs:/data/appjobs
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/tools/proteinmpnn_official:/data/tools/proteinmpnn_official
      - /data:/data
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    env_file:
      - ../frontend/.env
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped
